### ISSUE TITLE
SerialsSolutions access check logic is broken

### ISSUE THREAD

**Issue by kspurgin** [UNC-Libraries/Ebook-Access-Checker#8]
SerialsSolutions' new search results page now returns identical HTML source, regardless of your search results. 

We are looking into a workaround/fix for this.

**Comment by ldss-jm** [comment]
We implemented a workaround.

The script wasn't executing the angular.js on the new search results page (and still doesn't). For SerialsSolutions only, the script now extracts search criteria from the url it is given and manually passes it to the api their search results page is currently calling. If the script cannot extract the search criteria because it does not recognize the URL structure, it will output "Unknown URL structure." for that URL. If such URLs are reported, it should be possible to make the script accommodate their structure.
